INSERT INTO PRODUCT (ID,NAME,VERSION) VALUES (5,'Ucuz Ayfon',0);
INSERT INTO PRODUCT (ID,NAME,VERSION) VALUES(10,'Mavi Tişört',0);
INSERT INTO CATEGORY (ID,NAME,VERSION) VALUES(100,'Kazak',0);
INSERT INTO CATEGORY (ID,NAME,VERSION) VALUES(200,'Gömlek',0);